<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        
        <PackageTags>$(StuffTags);erdos renyi</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\stuff.graph.algorithms.net\stuff.graph.algorithms.net.csproj"/>
    </ItemGroup>
</Project>
