<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\stuff.graph.astar.net\stuff.graph.astar.net.csproj" />
      <ProjectReference Include="..\stuff.graph.dependencyinjection.net\stuff.graph.dependencyinjection.net.csproj" />
      <ProjectReference Include="..\stuff.graph.dijkstra.net\stuff.graph.dijkstra.net.csproj" />
      <ProjectReference Include="..\stuff.graph.sortingbarrier.net\stuff.graph.sortingbarrier.net.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

</Project>
