<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        
        <PackageTags>$(StuffTags);dependency injection</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\stuff.graph.astar.net\stuff.graph.astar.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.cost.net\stuff.graph.cost.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.dijkstra.net\stuff.graph.dijkstra.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.dorogovtsevmendes.net\stuff.graph.dorogovtsevmendes.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.erdosrenyi.net\stuff.graph.erdosrenyi.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.mwst.net\stuff.graph.mwst.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.pagerank.net\stuff.graph.pagerank.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.sortingbarrier.net\stuff.graph.sortingbarrier.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.wattsstrogatz.net\stuff.graph.wattsstrogatz.net.csproj"/>
        <ProjectReference Include="..\stuff.graph.wcc.net\stuff.graph.wcc.net.csproj"/>
    </ItemGroup>

</Project>
