<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>

        <PackageTags>$(StuffTags);dorogovtsev mendes</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\stuff.graph.algorithms.net\stuff.graph.algorithms.net.csproj"/>
    </ItemGroup>
</Project>
